apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: myrepo/api-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: INFLUXDB_URL
              value: "http://influxdb:8086"
            - name: OAUTH2_PROVIDER_URL
              value: "https://auth.example.com"
