apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: queue-consumer
  template:
    metadata:
      labels:
        app: queue-consumer
    spec:
      containers:
        - name: queue-consumer
          image: myrepo/queue-consumer:latest
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: INFLUXDB_URL
              value: "http://influxdb:8086"
